version: "0.0.1"
services:
    web :
      build:
        context : .
      image: node-app:${IMAGE_TAG}
      ports: 
        - "5000:5000"
      environment:
        - NODE_ENV=development
      restart: always


